term.clear()
term.setCursorPos(1,1)
term.write("BertOS v2.0")
term.setCursorPos(1,3)
term.write("Welcome to the command prompt")
term.setCursorPos(1,4)
term.write("To return to the menu, type 'back'")
term.setCursorPos(1,5)
term.write("----------------------------------")
term.setCursorPos(1,6)
