local monitor = peripheral.find("monitor")
monitor.setTextScale(1)
monitor.clear()
monitor.setCursorPos(1,1)
monitor.write("STR: 12")
monitor.setCursorPos(1,2)
monitor.write("DEX: 14")
monitor.setCursorPos(1,3)
monitor.write("CON: 12")
monitor.setCursorPos(1,4)
monitor.write("INT: 9")
monitor.setCursorPos(1,5)
monitor.write("WIS: 7")
monitor.setCursorPos(1,6)
monitor.write("CHA: 18")
monitor.setCursorPos(1,7)
