local compter = term.current()
local monitor = peripheral.find("monitor")
monitor.setBackgroundColor(colors.black)
monitor.setTextScale(0.5)
monitor.setCursorPos(1,1)
monitor.clear()
term.redirect(peripheral.find("monitor"))
paintutils.drawImage(paintutils.loadImage("monitorImages/images/goblin"),1,1)
monitor.setBackgroundColor(colors.black)
term.redirect(compter)
monitor.setTextColor(1)
monitor.setCursorPos(30,7)
monitor.write("BREE YARK")
monitor.setCursorPos(30,8)
monitor.write("Im a gross lil GOBLIN INNIT")
monitor.setCursorPos(30,9)
monitor.write("(ya fat twat bastard)")

