local compter = term.current()
local monitor = peripheral.find("monitor")
monitor.setBackgroundColor(colors.black)
monitor.setTextScale(0.5)
monitor.setCursorPos(1,1)
monitor.clear()
term.redirect(peripheral.find("monitor"))
paintutils.drawImage(paintutils.loadImage("testPaint.nfp"),1,1)
monitor.setBackgroundColor(colors.black)
term.redirect(compter)
monitor.setTextColor(1)
monitor.setCursorPos(35,7)
monitor.write("Weh")
